{% set name = "kconfigwidgets" %}
{% set version = "5.73.0" %}
{% set major_minor = ".".join(version.split(".")[:2]) %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://download.kde.org/stable/frameworks/{{ major_minor }}/kconfigwidgets-{{ version }}.tar.xz
  sha256: ed8a0a8158f895aebd46c4a725f77178d942cd9476a864a615a9df343da51f8e

build:
  number: 0
  skip: true  # [not linux]
  run_exports:
    - {{ pin_subpackage('kconfigwidgets', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - extra-cmake-modules >={{ major_minor }}
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
  host:
    - xorg-libxfixes  # [linux]
    - xorg-libxext
    - qt
    - kauth >={{ major_minor }}
    - ki18n >={{ major_minor }}
    - kcodecs >={{ major_minor }}
    - kconfig >={{ major_minor }}
    - kguiaddons >={{ major_minor }}
    - kcoreaddons >={{ major_minor }}
    - kwidgetsaddons >={{ major_minor }}

test:
  commands:
    - test -f ${PREFIX}/lib/libKF5ConfigWidgets.so

about:
  home: https://api.kde.org/frameworks/kconfigwidgets/html/index.html
  license: GPL-v2
  license_family: GPL
  license_file: COPYING
  summary: Widgets for configuration dialogs
  description: |
    KConfigWidgets provides easy-to-use classes to create configuration dialogs,
    as well as a set of widgets which uses KConfig to store their settings.
  dev_url: https://cgit.kde.org/kconfigwidgets.git/tree

extra:
  recipe-maintainers:
    - scopatz
