{% set name = "kconfigwidgets" %}
{% set version = "5.75.0" %}
{% set major_minor = ".".join(version.split(".")[:2]) %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://download.kde.org/stable/frameworks/{{ major_minor }}/kconfigwidgets-{{ version }}.tar.xz
  sha256: cd99dc233d1aaf30fbb910f2f268cffc1e11d3480b7c592d2a566aaf4812f083

build:
  number: 0
  skip: true  # [not linux]
  run_exports:
    - {{ pin_subpackage('kconfigwidgets', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - extra-cmake-modules >={{ major_minor }}
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
  host:
    - xorg-libxfixes  # [linux]
    - xorg-libxext
    - qt
    - kauth >={{ major_minor }}
    - ki18n >={{ major_minor }}
    - kcodecs >={{ major_minor }}
    - kconfig >={{ major_minor }}
    - kguiaddons >={{ major_minor }}
    - kcoreaddons >={{ major_minor }}
    - kwidgetsaddons >={{ major_minor }}

test:
  commands:
    - test -f ${PREFIX}/lib/libKF5ConfigWidgets.so

about:
  home: https://api.kde.org/frameworks/kconfigwidgets/html/index.html
  license: BSD-3-Clause AND GPL-2.0-or-later AND LGPL-2.0-only AND LGPL-2.0-or-later AND LGPL-2.1-only AND LGPL-3.0-only AND LicenseRef-KDE-Accepted-LGPL AND MIT
  license_file:
    - LICENSES/BSD-3-Clause.txt
    - LICENSES/GPL-2.0-or-later.txt
    - LICENSES/LGPL-2.0-only.txt
    - LICENSES/LGPL-2.0-or-later.txt
    - LICENSES/LGPL-2.1-only.txt
    - LICENSES/LGPL-3.0-only.txt
    - LICENSES/LicenseRef-KDE-Accepted-LGPL.txt
    - LICENSES/MIT.txt
  summary: Widgets for configuration dialogs
  description: |
    KConfigWidgets provides easy-to-use classes to create configuration dialogs,
    as well as a set of widgets which uses KConfig to store their settings.
  dev_url: https://cgit.kde.org/kconfigwidgets.git/tree

extra:
  recipe-maintainers:
    - scopatz
