{% set name = "kconfigwidgets" %}
{% set version = "5.68.0" %}
{% set major_minor = ".".join(version.split(".")[:2]) %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://download.kde.org/stable/frameworks/{{ major_minor }}/kconfigwidgets-{{ version }}.tar.xz
  sha256: f50421e9dbb6669e8d7c10605f7779ad03f30ea7c9c4451a70a7be66cd9df995

build:
  number: 0
  skip: true  # [not linux]
  run_exports:
    - {{ pin_subpackage('kconfigwidgets', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - extra-cmake-modules
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
  host:
    - xorg-libxfixes  # [linux]
    - xorg-libxext
    - qt
    - kauth
    - ki18n
    - kcodecs
    - kconfig
    - kguiaddons
    - kcoreaddons
    - kwidgetsaddons

test:
  commands:
    - test -f ${PREFIX}/lib/libKF5ConfigWidgets.so

about:
  home: https://api.kde.org/frameworks/kconfigwidgets/html/index.html
  license: GPL-v2
  license_family: GPL
  license_file: COPYING
  summary: Widgets for configuration dialogs
  description: |
    KConfigWidgets provides easy-to-use classes to create configuration dialogs,
    as well as a set of widgets which uses KConfig to store their settings.
  dev_url: https://cgit.kde.org/kconfigwidgets.git/tree

extra:
  recipe-maintainers:
    - scopatz
