travis:
  secure:
    BINSTAR_TOKEN: HiV7U76dbyWe8FC1fuW67TGU8nXFAfHFNpfnuG5+8edRPLsBlFIFnBPd9vT5x/g6cJ/4A3CX/J0OQbQo00+UhlKK4hyQR26POXDVojElGMqWJi81KQV/pktLhkyJviqWK60CBqfz3cGSM6/DUxaQ96vbMHlfnVURHyGtreLkiXsYF7XvEDNIGheX5K1AHHlbfsix/aCqVUNxZCBwOU6adIee7JfsfBvHCTney2rMaRlxGe+Y7sb9TMhgR1CFovdVLwXwRUEwIm2Se8Hhn9wvF/ImE8/JJATWBY7fX25r2+hQ4tAfJrJk7DeWxXLVfa78POeOC020B+/8XjaYEj2kh+KxaIzcEXGjlacxOixbkgehePVU3fcUnbvd09Altav8uGzgXeQXEk23v/En3xg8fjwmVG2+9nb4VZD5wedJfhad3TAQEFazSD7rPe2X5bKOG+3SLN3N+Ivjv3Fw5N0yFgFfsDkAZSCJjSmuTalvIpX9sKFmapG/dyt79wD2/fDXcZ57DdErIpNIwvd10J+WWsGhhs5ZnMCZ8EQ3aiVaTV1pV9gLzDY/zPJDczIJFzosqdK71dlhrLdiDOgsUjGAYhcT1oUBbNpm+48DPBJEQpntfMwuUpxVudb2rNBUQ/rEu3L0HAkaRIo6ydxQxg7Ns8FiSv6Xp+9/cn4gnTwLY1M=
conda_forge_output_validation: true
bot:
  check_solvable: True
  
